### ISSUE TITLE
Wrong formatted syntax in all string functions

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-de#270]
![grafik](https://user-images.githubusercontent.com/9639361/56869090-02227b00-69fc-11e9-9073-165601115b49.png)

**Comment by per1234** [comment]
I noticed that too. Some of these were fixed in the reference-en repository, but I think they went the wrong way by removing the backticks and leaving the code fences, contrary to the standard established by the [sample reference page](https://github.com/arduino/reference-en/blob/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc).

I was going to cherry pick those commits to this repository, but then I thought that I wouldn't bother and instead wait for it to be fixed properly when https://github.com/arduino/reference-en/pull/559 is merged. I'm not sure how long it will be before that happens, so it might make sense to go ahead and fix the issue right away instead of waiting.

**Comment by SeppPenner** [comment]
I will check this and try to provide a fix. I'm not completely sure what the problem is there, however. I mean, the "`" should be rendered as code, shouldn't it?

**Comment by per1234** [comment]
Ah, I misspoke, I was thinking of the same problem as it occurs in the "Characters" functions:
https://www.arduino.cc/reference/de/language/functions/characters/isalphanumeric/

![Clipboard01](https://user-images.githubusercontent.com/8572152/57126988-ccef9300-6d43-11e9-97fb-0d098a1715a1.png)

Here's the pull request that "fixed" those functions in the reference-en repository: https://github.com/arduino/reference-en/pull/471

However, the fix was to remove the backquotes and leave the code fencing like this:
```asciidoc
[source,arduino]
----
isAlphaNumeric(thisChar)
----
```
which renders like this:
```
isAlphaNumeric(thisChar)
```
However, if you look at the sample reference page, you can see that the code fencing should have been removed and the backquotes left instead:
```asciidoc
`isAlphaNumeric(thisChar)`
```
which renders like this:
`isAlphaNumeric(thisChar)`

**Comment by SeppPenner** [comment]
@per1234 Thank you for the investigation. I will change this.
